site_name: "Advanced NLP Classes"
nav:
  - Classes:
    - Overview: index.md
    - "Session 1: Introduction to the class": chapter1/README.md
    - "Session 2: Deep Learning for NLP": chapter2/README.md
    - "Session 3: Word Embeddings": chapter3/README.md
    - "Session 4: Practical NLP - 1": chapter4/README.md
    - "Session 5: Transformers & BERT": chapter5/README.md
    - "Session 6: Few-Shot learning & Transfer Learning": chapter6/README.md
    - "Session 7: Injustice & Biases in NLP": chapter7/README.md
    - "Session 8: Practical NLP - 2": chapter8/README.md
    - "Session 9: LLM introduction": chapter9/README.md
    - "Session 10: Agents": chapter10/README.md
  - Notebooks: notebooks.md
  - Resources: resources.md
  - Evaluations:
    - Overview: evaluations/evaluations.md
    - "First Home Assignment": evaluations/first-home-assignment.md
    - "Second Home Assignment": evaluations/second-home-assignment.md
    - "Final Project": evaluations/final-project.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Add repository URL to show GitHub link at the top
repo_url: https://github.com/agombert/AdvancedNLPClasses
repo_name: agombert/AdvancedNLPClasses

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_widgets: true

# Configuration for static files (PDFs)
use_directory_urls: true

# Use 'extra' to copy additional files (instead of 'extra_files')
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agombert/AdvancedNLPClasses

# Add this to handle static files like PDFs
docs_dir: docs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
