site_name: "Advanced NLP Classes"
nav:
  - Classes:
    - Overview: index.md
    - "Session 1: Introduction to the class": chapter1/README.md
    - "Session 2: Deep Learning for NLP": chapter2/README.md
    - "Session 3: Word Embeddings": chapter3/README.md
    - "Session 4: Practical NLP - 1": chapter4/README.md
    - "Session 5: Transformers & BERT": chapter5/README.md
    - "Session 6: Few-Shot learning & Transfer Learning": chapter6/README.md
    - "Session 7: Injustice & Biases in NLP": chapter7/README.md
    - "Session 8: Practical NLP - 2": chapter8/README.md
    - "Session 9: LLM introduction": chapter9/README.md
    - "Session 10: Agents": chapter10/README.md
  - Notebooks: notebooks.md
  - Resources: resources.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocs-jupyter
  - search

# Configuration pour les fichiers statiques (PDFs)
use_directory_urls: true

# Redirection automatique vers index.md
extra:
  homepage: index.md

# Fichiers à copier dans le répertoire de build
extra_files:
  - .nojekyll
