name: Build and Deploy

on:
  push:
    branches: [ "main" ]

# Autorise le déploiement sur Pages avec le token GitHub
permissions:
  contents: read
  pages: write
  id-token: write

# Empêche deux déploiements simultanés
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check PDFs directory
        run: |
          echo "=== Checking docs/pdfs directory ==="
          ls -la docs/pdfs/ || echo "docs/pdfs directory does not exist"
          echo "=== Checking PDF file ==="
          ls -la docs/pdfs/2025_BSE_NLP_Session_1.pdf || echo "PDF file not found"

      - name: Build MkDocs
        run: poetry run mkdocs build --clean

      - name: Ensure .nojekyll file exists
        run: |
          touch site/.nojekyll
          echo "=== Checking site directory content ==="
          ls -la site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
