name: Build and Deploy

on:
  push:
    branches: [ "main" ]

# Autorise le déploiement sur Pages avec le token GitHub
permissions:
  contents: read
  pages: write
  id-token: write

# Empêche deux déploiements simultanés
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    # On force ici Ubuntu 22.04 plutôt que 'ubuntu-latest' ou 'ubuntu-24.04'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check PDFs directory
        run: |
          echo "=== Checking docs/pdfs directory ==="
          ls -la docs/pdfs/ || echo "docs/pdfs directory does not exist"
          echo "=== Checking PDF file ==="
          ls -la docs/pdfs/2025_BSE_NLP_Session_1.pdf || echo "PDF file not found"

      - name: Build MkDocs
        run: poetry run mkdocs build --clean

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Utiliser une approche alternative pour déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site  # Le répertoire généré par "mkdocs build"
          branch: gh-pages  # La branche où déployer
